version: "3.8"
services:
  frontend:
    container_name: snap-sorter-frontend-prod
    image: snap-sorter-frontend-prod
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    depends_on:
      - db
    env_file:
      - ./frontend/.env.production
    ports:
      - 80:3000
     volumes:
      - ./frontend/pages:/app/pages
      - ./frontend/components:/app/components
      - ./frontend/styles:/app/styles
  db:
    image: postgres:latest
    container_name: snap-sorter-database-prod
    restart: always
    env_file:
      - ./frontend/.env.production
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
