version: "3.8"
services:
  next-app:
    container_name: snap-sorter-app-prod
    image: snap-sorter-app-prod
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
    depends_on:
      - db
    env_file:
      - ./next-app/.env.production
    ports:
      - 3000:3000
    volumes:
      - ./next-app/pages:/app/pages
      - ./next-app/components:/app/components
      - ./next-app/styles:/app/styles
      - ./uploads:/app/uploads
  db:
    image: postgres:latest
    container_name: snap-sorter-database-prod
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./next-app/.env.production
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
