version: "3.8"
services:
  next-app:
    container_name: snap-sorter-app-dev
    image: snap-sorter-app-dev
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    env_file:
      - ./next-app/.env.development
    ports:
      - 3000:3000
    volumes:
      - ./next-app/pages:/app/pages
      - ./next-app/components:/app/components
      - ./next-app/styles:/app/styles
      - ./uploads:/app/uploads
  db:
    image: postgres:latest
    container_name: snap-sorter-database-dev
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./next-app/.env.development
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
