version: "3.8"
services:
  frontend:
    container_name: snap-sorter-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    env_file:
      - ./frontend/.env.development
    ports:
      - 5173:5173
      - 5555:5555
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/prisma:/app/prisma
    image: snap-sorter-frontend-dev
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: snap-sorter-database-dev
    restart: always
    env_file:
      - ./frontend/.env.development
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
